language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.1

before_script:
    - phpenv config-rm xdebug.ini
    - composer self-update
    
install:
    - composer install --prefer-dist

script: 
    - vendor/bin/phpunit
